name: iOS starter workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build .app and Convert to .ipa
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod setup
          cd iosbuildtest2
          pod install

      - name: Build .app (Simulator)
        run: |
          cd iosbuildtest2
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "SCHEME=$default" >> $GITHUB_ENV
          xcodebuild -workspace hspproj.xcworkspace -scheme "$SCHEME" -sdk iphonesimulator -configuration Release build

      - name: Find .app Path
        run: |
          cd iosbuildtest2
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Convert .app to .ipa
        run: |
          mkdir -p Payload
          cp -R "${{ env.APP_PATH }}" Payload/
          zip -r hsp3dish.ipa Payload

      - name: Upload .ipa as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hsp3dish
          path: hsp3dish.ipa
