name: iOS starter workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Export IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          cd iosbuildtest2
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Export IPA
        env:
          scheme: ${{ 'default' }}
        run: |
          # Export the IPA from the archive
          cd iosbuildtest2
          if [ $scheme = default ]; then scheme=$(cat default); fi
          xcodebuild -scheme "$scheme" -configuration Release -exportPath $PWD/build build
      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hsp3dish
          path: $PWD/build/*.app
