name: iOS starter workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build .app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          cd iosbuildtest2
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]") 
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build .app
        run: |
          cd iosbuildtest2
          scheme=$(cat default)
          xcodebuild -scheme "$scheme" -allowProvisioningUpdates -configuration Release build

      - name: Find .app Path
        run: |
          cd iosbuildtest2
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV

      - name: Upload .app as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hsp3dish
          path: ${{ env.APP_PATH }}
